### PR TITLE
update podspec to 1.0.2

### PR DESCRIPTION
**Pull request by VilemKurz**

### CODE REVIEW

**Comment by tomassliz** [comment]
You didn't update the version in project file? Is it intent? I think that the version in podspec and in project file should be equal.

**Comment by tomassliz** [comment]
Plus the tag `1.0.2` is placed on feature branch.

**Comment by VilemKurz** [comment]
@tomassliz Where else would you place the tag? As soon as feature branch is merged it moves to master. It is a catch 22. Will you update podspec after you merge to master? Then the feature is not complete, because it is not reflected in a podspec. So I decided to keep tag & podspec version in sync, and make both of them a part of feature branch. This way also podspec is checked via CI. And publish podspec in trunk as soon as the feature is merged. Do you find this to be a problem?

**Comment by VilemKurz** [comment]
@tomassliz AFAIK it is not needed to keep version in a project file updated. Do you have a reason for it?

**Comment by tomassliz** [comment]
I thought that the tag should be moved to the master branch.

And regarding the version - someone can use this framework as a submodule so it's a good practice to have something like versioning there too. Another reason can be Carthage support. But you're right, it's only minor change from the "nice to have" category. Anyway every good and well-known 3rd party framework do it this way.

**Comment by VilemKurz** [comment]
The tag is tied to commit. So as soon as the commit becomes a master branch commit (as soon as it is merged) also the tag becomes a master branch tag. Or am I missing something?

**Comment by tomassliz** [comment]
No, it's right. I'm just influenced by the git-flow. It says that tags should be created only on master branch merge commits. But it's detail and you don't use git-flow, so never mind.

**Pull request merged**
